import test from 'node:test';
import assert from 'node:assert/strict';
import {premarketSlot,equityUniverse,buildPremarket,observePremarket} from '../server/premarket.js';
import {createScheduledPremarketHandler} from '../server/scheduledPremarket.js';
const now=Date.parse('2026-10-01T08:45:00+05:30');
const rows=equityUniverse([{segment:'NSE_EQ',instrument_type:'EQ',security_type:'NORMAL',instrument_key:'NSE_EQ|INE000A01010',name:'EXAMPLE INDUSTRIES LTD',short_name:'Example Industries',trading_symbol:'EXAMPLE'}]);
const article=(title='Example Industries announces results',publishedAt=new Date(now-60000).toISOString())=>({title,publishedAt,url:'https://example.com/news',source:'Publisher'});
const args=(articles=[article()])=>({universe:{rows,source:'test-master',observedAt:new Date(now).toISOString()},articles,sourceHealth:[{source:'test',status:'available'}],startedAt:new Date(now).toISOString(),observedAt:new Date(now+1000).toISOString()});
test('IST slots cannot backfill outside weekday research hours',()=>{assert.equal(premarketSlot(now).slot,'08:45');assert.equal(premarketSlot(Date.parse('2026-10-01T09:16:00+05:30')),null);assert.equal(premarketSlot(Date.parse('2026-10-03T08:45:00+05:30')),null);assert.equal(premarketSlot(now+4*60000).late,true);assert.equal(premarketSlot(now+15*60000).slot,'09:00');});
test('only verified normal NSE equities enter mapping',()=>{assert.throws(()=>equityUniverse([{segment:'NSE_FO'}]));assert.equal(rows.length,1);});
test('shortlist excludes future, old, price-only and ambiguous identity evidence',()=>{const input=args([article(),article(),article('Example Industries announces profits',new Date(now+1).toISOString()),article('Example Industries results',new Date(now-2*86400000).toISOString()),article('Example Industries share price today')]);const result=buildPremarket(input);assert.equal(result.candidates.length,1);assert.equal(result.candidates[0].evidence.length,1);assert.equal(result.candidates[0].direction,'UNDETERMINED');const ambiguous=buildPremarket({...args(),universe:{...input.universe,rows:[...rows,{...rows[0],instrumentKey:'other'}]}});assert.equal(ambiguous.candidates.length,0);assert.equal(ambiguous.coverage.ambiguous,1);});
test('missing data remains unavailable; partial source failures remain visible',async()=>{await assert.rejects(observePremarket({master:async()=>{throw new Error('failed')},news:async()=>({articles:[]})}));const result=await observePremarket({now:()=>now,master:async()=>args().universe,news:async(_q,{topic})=>{if(topic==='market')throw new Error('rate limited');return {articles:[article()]};}});assert.equal(result.status,'PARTIAL');assert.equal(result.candidates.length,1);});
function response(){return {code:200,body:null,setHeader(){},status(code){this.code=code;return this;},json(body){this.body=body;return this;}};}const secret='a'.repeat(32);
test('scheduled capture rejects unauthenticated calls before acquiring or storing data',async()=>{let called=false;const handler=createScheduledPremarketHandler({now:()=>now,secret:()=>secret,store:()=>{called=true;throw Error();}});const res=response();await handler({method:'POST',headers:{},body:{}},res);assert.equal(res.code,401);assert.equal(called,false);});
test('scheduled duplicate does not rerun acquisition or mutate history',async()=>{let observed=false;const handler=createScheduledPremarketHandler({now:()=>now,secret:()=>secret,store:()=>({read:async()=>[{slot:'08:45',published_at:'original'}]}),observe:async()=>{observed=true;}});const res=response();await handler({method:'POST',headers:{authorization:'Bearer '+secret},body:{}},res);assert.equal(res.body.status,'ALREADY_RECORDED');assert.equal(observed,false);});
test('failed acquisition persists failure evidence rather than a successful empty shortlist',async()=>{let stored;const handler=createScheduledPremarketHandler({now:()=>now,secret:()=>secret,store:()=>({read:async()=>[],save:async(_date,_slot,report)=>(stored=report)}),observe:async()=>{throw Error();}});const res=response();await handler({method:'POST',headers:{authorization:'Bearer '+secret},body:{}},res);assert.equal(res.code,503);assert.equal(stored.status,'UNAVAILABLE');});

test('indexed financial directories and generic stock roundups are not catalysts',()=>{for(const title of ['Half Yearly Results, Half yearly Earnings for Example Industries','Example Industries Q3 Results 2026 - Find Example Industries Q3 Earnings Result','Dividend gems: 9 stocks with Example Industries | Check returns'])assert.equal(buildPremarket(args([article(title)])).candidates.length,0);});
