import {useEffect,useState} from 'react';
import {fetchLiveIPOs,getLastIPOFetchError,type IPOData} from '../services/ipoService';
import {apiUrl} from '../utils/apiUrl';
import {formatIST} from '../services/tradingTime';
interface News {query:string;receivedAt:string;source:string;status:string;articles:{title:string;source:string;url:string;publishedAt:string;tone:string;fresh:boolean}[];summary:{status:string;sampleSize:number;publishers:number;counts:{positive:number;negative:number;unclear:number};method:string}}
const topics=[['market','Market & indices'],['company','Company news'],['sectors','Sectors'],['earnings','Results & corporate events'],['macro','Macro & institutional flows'],['derivatives','Options & futures context']] as const;
export function MarketNewsPage({segment='intraday'}:{segment?:string}){
 const [view,setView]=useState<'trading'|'ipo'>('trading');
 const [topic,setTopic]=useState(segment==='options'||segment==='futures'?'derivatives':'market');
 const [days,setDays]=useState(segment==='long-term'?'30':segment==='short-term'?'7':'1');
 const effectiveTopic=view==='ipo'?'ipo':topic;
 const [input,setInput]=useState(''),[query,setQuery]=useState(''),[revision,setRevision]=useState(0),[news,setNews]=useState<News|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[expanded,setExpanded]=useState(false);
 const [ipos,setIpos]=useState<IPOData[]>([]),[ipoError,setIpoError]=useState(''),[ipoLoading,setIpoLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setExpanded(false);setNews(null);setError('');
 fetch(apiUrl('/api/research?q='+encodeURIComponent(query)+'&topic='+effectiveTopic+'&days='+days),{signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||'News unavailable');return body as News;}).then(data=>{if(!controller.signal.aborted)setNews(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[query,revision,effectiveTopic,days]);
 useEffect(()=>{if(view!=='ipo')return;let active=true;setIpoLoading(true);fetchLiveIPOs().then(data=>{if(active){setIpos(data);setIpoError(getLastIPOFetchError()||'');}}).catch(()=>{if(active)setIpoError('IPO source unavailable');}).finally(()=>{if(active)setIpoLoading(false);});return()=>{active=false;};},[view]);
 const matching=ipos.filter(ipo=>!query||ipo.name.toLowerCase().includes(query.toLowerCase()));
 return <div className="space-y-6"><section className="card space-y-4"><div><p className="text-sm text-[var(--text-muted)]">MARKET RESEARCH</p><h1 className="text-2xl font-semibold">Trading news & market context</h1><p>Research market-moving developments for intraday, short-term, long-term, options and futures decisions.</p></div>
 <div className="news-controls flex flex-wrap gap-3" aria-label="Research view"><button className="rounded-lg border px-4 py-2" aria-pressed={view==='trading'} onClick={()=>setView('trading')}>Trading news</button><button className="rounded-lg border px-4 py-2" aria-pressed={view==='ipo'} onClick={()=>setView('ipo')}>IPO / GMP</button></div>
 {view==='trading'&&<nav aria-label="Trading news topics" className="news-controls flex flex-wrap gap-2">{topics.map(([id,label])=><button key={id} aria-pressed={topic===id} className="rounded-lg border px-3 py-2" onClick={()=>setTopic(id)}>{label}</button>)}</nav>}
 <label className="flex flex-wrap items-center gap-3">News window<select className="rounded-lg border p-2" value={days} onChange={e=>setDays(e.target.value)}><option value="1">Last 24 hours</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></label>
 <form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();setQuery(input.trim());setRevision(r=>r+1);}}><label className="flex-1 min-w-0">Company or topic<input className="w-full rounded-lg border p-3" maxLength={100} value={input} onChange={e=>setInput(e.target.value)} placeholder={view==='ipo'?'IPO company name…':'Reliance, HDFC Bank, crude oil…'}/></label><button type="submit" className="self-end rounded-lg border px-4 py-3" disabled={loading}>{loading?'Searching…':'Search'}</button></form>
 {view==='ipo'&&<a className="underline" href="#ipo-observations">Jump to IPO grey-market observations</a>}
 {view==='trading'&&<p className="notice">Use dated news to investigate catalysts, results, policy changes and underlying-index events. For options and futures, this is underlying-market context; contract quotes, liquidity, volatility and execution checks are still required.</p>}
 <p className="text-sm text-[var(--text-muted)]">Headlines link to source coverage. This view does not change buy/sell signals or automatically place paper trades.</p>
 </section>
 <section className="card space-y-4" aria-label="News evidence"><h2 className="text-xl font-semibold">{query?query+' · ':''}{view==='ipo'?'IPO / GMP':topics.find(t=>t[0]===topic)?.[1]} · headline evidence</h2>{loading&&<p role="status">Loading source observations…</p>}{error&&<p role="alert">{error}</p>}{news&&<><p className="text-sm">{news.source} · Retrieved {formatIST(news.receivedAt)} · up to five minutes cached · sample of up to 50 results over {days} day(s)</p><div className="notice"><strong>{news.summary.status==='available'?'Headline tone counts':'Insufficient recent evidence for headline tone'}</strong><p>{news.summary.sampleSize} headlines · {news.summary.publishers} publishers · {news.summary.counts.positive} positive · {news.summary.counts.negative} negative · {news.summary.counts.unclear} unclear</p><p>{news.summary.method}</p></div>{news.articles.length===0&&<p>No dated headlines returned for this search. This does not establish neutral market sentiment.</p>}<ul className="space-y-4">{news.articles.slice(0,expanded?50:10).map(article=><li key={article.url} className="border-b pb-4 break-words"><a className="font-medium underline" href={article.url} target="_blank" rel="noopener noreferrer">{article.title}</a><p className="text-sm text-[var(--text-muted)]">{article.source} · Published {formatIST(article.publishedAt)} · {article.fresh?article.tone+' wording':'Older than 24h; excluded from counts'}</p></li>)}</ul>{news.articles.length>10&&<button className="underline" onClick={()=>setExpanded(v=>!v)}>{expanded?'Show fewer headlines':'Show all headlines'}</button>}</>}</section>
 {view==='ipo'&&<section id="ipo-observations" className="card space-y-4"><h2 className="text-xl font-semibold">IPO grey-market observations</h2><p>Unofficial third-party indications, not exchange prices or guaranteed listing gains. Source publication time is unverified; retrieval time does not prove quote freshness.</p>{ipoLoading&&<p role="status">Loading IPO source…</p>}{ipoError&&<p role="status">{ipoError}</p>}{!ipoLoading&&!ipoError&&matching.length===0&&<p>No matching IPO observations.</p>}<div className="grid gap-4 md:grid-cols-2">{matching.map((ipo,i)=><article key={ipo.id||ipo.name+i} className="rounded-lg border p-4 min-w-0 space-y-2"><h3 className="font-semibold break-words">{ipo.name}</h3><p>{ipo.status} · Reported GMP: {ipo.gmp==null?'Unavailable':'₹'+ipo.gmp.toLocaleString('en-IN')} {ipo.gmp==null||ipo.gmp_pct==null?'':'('+ipo.gmp_pct.toFixed(1)+'%)'}</p><p className="text-sm">InvestorGain · Retrieved {formatIST(ipo.receivedAt)}</p><button className="underline" onClick={()=>{setInput(ipo.name);setQuery(ipo.name);setRevision(r=>r+1);window.scrollTo({top:0});}}>Search related headlines</button></article>)}</div></section>}</div>;
}
