import {useEffect,useState} from 'react';
import {apiUrl} from '../utils/apiUrl';
import {formatIST,istDate} from '../services/tradingTime';
interface Evidence {id:string;title:string;url:string;source:string;publishedAt:string;observedAt:string;categories:string[]}
interface Candidate {instrumentKey:string;symbol:string;name:string;publisherCount:number;eventTypes:string[];evidence:Evidence[]}
interface Report {status:string;mode:string;startedAt:string;observedAt:string;publishedAt?:string;late?:boolean;beforeRegularOpen?:boolean;error?:string;method?:string;universe?:{count:number;observedAt:string};coverage?:{headlines:number;unmatched:number;ambiguous:number};sourceHealth?:{topic:string;status:string;count:number|null}[];missingEvidence?:string[];candidates:Candidate[]}
interface Snapshot {session_date:string;slot:string;published_at:string;report:Report}
export function PremarketPage(){
 const [date,setDate]=useState(istDate()),[rows,setRows]=useState<Snapshot[]>([]),[dates,setDates]=useState<string[]>([]),[slot,setSlot]=useState('08:45'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[preview,setPreview]=useState<Report|null>(null),[previewing,setPreviewing]=useState(false),[previewError,setPreviewError]=useState('');
 useEffect(()=>{let active=true;const controller=new AbortController();setRows([]);setPreview(null);setLoading(true);setError('');
 const update=()=>fetch(apiUrl('/api/premarket?date='+date),{signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||'Research history unavailable');return body;}).then(body=>{if(active){setRows(body.reports);setDates(body.dates);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});
 void update();const timer=setInterval(update,60000);return()=>{active=false;controller.abort();clearInterval(timer);};},[date]);
 const selected=rows.find(row=>row.slot===slot)||rows[0];
 const report=preview||selected?.report;
 async function getPreview(){setPreviewing(true);setPreviewError('');try{const response=await fetch(apiUrl('/api/premarket?preview=1'));const body=await response.json();if(!response.ok)throw new Error(body.error);setPreview(body.preview);}catch(e){setPreviewError(e instanceof Error?e.message:'Preview unavailable');}finally{setPreviewing(false);}}
 function exportReport(){if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(preview?{preview}:selected,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`premarket-${preview?'preview':date}-${preview?'now':selected?.slot.replace(':','')}.json`;link.click();URL.revokeObjectURL(url);}
 return <div className="space-y-6"><section className="card space-y-4"><p className="text-sm text-[var(--text-muted)]">BEFORE THE OPEN · SHARED RESEARCH</p><h1 className="text-2xl font-semibold">Pre-market watchlist</h1><p>Review company events before the session. Scheduled snapshots preserve what was observed then; later movements cannot rewrite the list.</p><p className="notice">Research candidates only. Price levels, liquidity, live order books, financial statements and investor identities are not verified by this news-based shortlist. No buy/sell signal or paper order is created.</p><div className="flex flex-wrap gap-3 items-end"><label>Research date<input className="block rounded-lg border p-2" type="date" value={date} max={istDate()} onChange={e=>{if(e.target.value){setDate(e.target.value);setSlot('08:45');}}}/></label><label>Saved snapshot<select className="block rounded-lg border p-2" value={selected?.slot||''} disabled={!rows.length} onChange={e=>{setSlot(e.target.value);setPreview(null);}}>{!rows.length&&<option value="">None recorded</option>}{rows.map(row=><option key={row.slot} value={row.slot}>{row.slot} IST {row.slot==='08:45'?'· morning shortlist':''}</option>)}</select></label><button className="rounded-lg border p-2" onClick={()=>void getPreview()} disabled={previewing}>{previewing?'Reading current sources…':'Preview current research'}</button>{preview&&<button className="underline" onClick={()=>setPreview(null)}>Return to saved history</button>}</div><p className="text-sm text-[var(--text-muted)]">Target capture: weekdays, every 15 minutes from 07:30–09:15 IST. The 08:45 snapshot is the morning shortlist. Holidays/session eligibility are not yet verified. History retains 35 days.</p>{dates.length>0&&<p className="text-sm">Recorded dates: {dates.slice(0,7).join(', ')}</p>}</section>
 {error&&<p className="notice" role="alert">{error}</p>}{previewError&&<p className="notice" role="alert">{previewError}</p>}{loading&&!report&&<p role="status">Loading shared history…</p>}{!loading&&!error&&!rows.length&&!preview&&<section className="card"><h2>No saved snapshot for {date}</h2><p>This does not mean no stocks qualified. A scheduled capture may not have run yet. Current previews are not saved or backdated into morning history.</p></section>}
 {report&&<><section className="card space-y-3"><h2 className="text-xl font-semibold">{preview?'Current preview · not saved':`${selected?.slot} IST snapshot`}</h2><p>{report.status} · {preview?'Does not prove pre-market selection':`Published ${formatIST(selected?.published_at)}`}</p><p>Collection started {formatIST(report.startedAt)} · Observed {formatIST(report.observedAt)}</p>{!preview&&<p>{report.beforeRegularOpen?'Recorded before regular-session opening time':'Recorded at/after regular-session opening time'}{report.late?' · Late invocation; inspect actual timestamps':''}</p>}{report.error&&<p role="alert">{report.error}</p>}{report.coverage&&<p>{report.universe?.count} mapped NSE equities · {report.coverage.headlines} unique dated headlines · {report.coverage.unmatched} unmatched · {report.coverage.ambiguous} ambiguous company matches excluded</p>}<p>{report.method}</p><ul>{report.sourceHealth?.map(s=><li key={s.topic}>{s.topic}: {s.status}{s.count===null?'':` · ${s.count} headlines`}</li>)}</ul><button className="underline" onClick={exportReport}>Export evidence JSON</button></section>
 <div className="grid gap-4 lg:grid-cols-2">{report.candidates.map((c,index)=><article key={c.instrumentKey} className="card min-w-0 space-y-3"><p className="text-sm">Research priority {index+1} · Direction undetermined</p><h2 className="text-xl font-semibold break-words">{c.symbol} · {c.name}</h2><p>{c.eventTypes.join(' · ')}</p><p className="text-sm">{c.publisherCount} publisher(s); syndicated coverage may repeat the same event. Not independent confirmation.</p><ul className="space-y-3">{c.evidence.map(e=><li key={e.id} className="border-t pt-3 break-words"><a className="underline" href={e.url} target="_blank" rel="noopener noreferrer">{e.title}</a><p className="text-sm">{e.source} · Published {formatIST(e.publishedAt)}</p></li>)}</ul><p className="notice">Before considering a trade: verify the original announcement, current price and spread, then define entry, invalidation and risk. Those checks remain incomplete here.</p></article>)}</div>{!report.candidates.length&&report.status!=='UNAVAILABLE'&&<p className="notice">No unambiguous company-event matches in this source sample. This is not an exhaustive market scan.</p>}</>}
 </div>;
}
